services:
  neo4j:
    image: neo4j:5.22.0
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/your_password
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*"
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
    volumes:
      - ./data:/data
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --spider http://localhost:7474 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 15

  backend:
    build:
      context: ./backend
    container_name: backend
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      - AZURE_OPENAI_DEPLOYMENT=${AZURE_OPENAI_DEPLOYMENT}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION}
      - AZURE_OPENAI_EMBEDDINGS_DEPLOYMENT=${AZURE_OPENAI_EMBEDDINGS_DEPLOYMENT}
      - AZURE_OPENAI_EMBEDDINGS_API=${AZURE_OPENAI_EMBEDDINGS_API}
      - AZURE_OPENAI_EMBEDDINGS_ENDPOINT=${AZURE_OPENAI_EMBEDDINGS_ENDPOINT}
    depends_on:
      neo4j:
        condition: service_healthy
  frontend:
      build:
        context: ./frontend
      container_name: frontend
      ports:
        - "5173:80"
      depends_on:
        - backend